### ISSUE TITLE
Follow up after API

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#206]
Running list of issues (https://github.com/aspnet/SignalR/pull/191#issuecomment-279020058):
- [ ] ~consider adding Disposed state~
- [ ] ~throw exception when sending and the connection is before Connected or in Disposed state~ #249
- [ ] ~fix a possible race when StartAsync is not awaited and StopAsync/Dispose is called~ #248
- [ ] ~HubConnection.Invoke should check the value returned by Connection.SendAsync~ #249
- [x] more unit tests for HubConnection (mostly around error conditions) - see IConnection
- [x] consider creating IConnection interface and enable passign IConnection to HubConnection. Would simplify testing HubConnection and will enable using HubConnection with custom connections (probably not common)
- [ ] ~event handlers should not run on main SignalR thread~ - #246
- [ ] ~simplify HubConnection ctors - ILoggerFactory should not be required, IInvocationAdapter?~ - #247
- [ ] ~Received event should not be raised after the connection is disposed (what about stopped)~ - #250

**Comment by moozzyk** [comment]
Created individual issues.
