### ISSUE TITLE
Java Client Work Plan

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#2482]
## Getting Started

- [ ]  Decide on Maven or Gradle
- [ ] Get an empty project into the repo under clients/java
- [ ] HubConnection - (not going to worry about HttpConnection for now)
    - [ ] 	Handshake - send hardcoded request
    - [ ] 	Only going to support JSON protocol for now
    - [ ] 	Basic Sending Invocations, no streaming to start
    - [ ] 	Register `On` method handlers to HubConnection
    - [ ] 	Stop HubConnection
- [ ]  Basic "Happy Path" tests
- [ ] Transports - Just websockets for now

## Next Steps

- [ ]  Get this integrated with our build infrastructure
- [ ] More thorough testing - End to End + unit testing 
- [ ] HttpConnection 
- [ ] InvokeAsync
- [ ] Ensure functionality with SignalR Service
- [ ] Configuration
- [ ] Streaming
- [ ] SSE
- [ ]  LongPolling
- [ ]  Transport Fallback

**Comment by mikaelm12** [comment]
cc @anurse @BrennanConroy @muratg

**Comment by anurse** [comment]
Looks good. Can you file an issue for Getting Started, we can create issues for the Next Steps after we start iterating.
