### ISSUE TITLE
SignalR - BIG ROCKS

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR#394]
## SignalR 2.x feature parity
- [ ] Hub discovery **preview2**
    - [ ] Pluggable hub discovery (non reflection based)
- [ ] ~Hub invocation progress (IProgress) (might be deprecated because of streaming)~
- [ ] ~Hub invocation pipeline~  
- [x] Overriding Hub and method names **preview1** (https://github.com/aspnet/SignalR/issues/625)
- [x] Supporting IUserIdProvider (https://github.com/aspnet/SignalR/issues/604)
- [x] `IHubConnectionContext` missing properties (https://github.com/aspnet/SignalR/issues/734)
   -  [x] Caller (Hub only) **preview1**
   -  [x] Others **preview1**
   -  [x] OthersInGroup **preview1**
   -  [x] AllExcept 
   -  [x] Groups **preview1**
    - [x] Clients **preview1**
    - [x] Users **preview1**

## Cross-cutting
- [ ] Protocol versioning **preview2** #289
- [x] Auth #552
  - [x] Authorize Attribute on EndPoints 
  - [x] Authorize Attribute on Hub
  - [x] Authorize Attribute on Hub methods
  - [x] Specify out pattern for JWT bearer auth. Write a sample at minimum and explore the API. (https://github.com/aspnet/SignalR/issues/1018) **preview1**
- [x] Negotiate
- [x] Bare WebSockets connection to server without Options. (**P2 preview1**) #1035
- Logging 
  - [ ] Connection ID as a token & date/time in each log line **preview1** #553
  - [x] Consistent, configurable logging in TypeScript client #485

## Server side
- [x] Move to pipelines **preview2** #615 
- [ ] Investigate HubLifetimeManager Refactoring **preview2** #1235 
- [x] Streaming hub responses
- [x] Timeouts 
- [x] Keep-alive #282 **preview1**

- [x] Hub
  - [x] Hub\<IClientProxy\> 
  - [x] Hub\<dynamic\> #554
  - [x] Hub\<interface\> #555
- Protocols:
  - [x] JSON
     - [x] Customizing JSON.NET settings (#261)
  - [x] MsgPack #543
- Scale-out
  - [ ] ServiceBus (**RTM**) #501 
  - [x] Redis #288  **preview1**
  - [x] Groups #584 **preview1**

## Client side
- [ ] ~~Proxy generation #290  **preview2**~~
- [ ] Transport Fallback #1373 
- [ ] Investigate Adding Reconnects **preview2** #1374 
- [ ] Client API redesign https://github.com/aspnet/SignalR/issues/900 **preview2**
- [x] Reusable Connection instances on Client.  **preview1**
- [x] Support cancelling Streaming results without client disconnection #898 **preview1**
- Clients:
  - [x] C#
  - [x] JS Browser
     - [ ] Typescript consumption (#239) [Open decision: ES5 vs ES6 by default?]
  - [x] JS on Node #556 

## Fundamentals
- [ ] "BrowserStack" (or something similar) for browser testing (#1019) **preview2**
- [ ] Performance Measurement Process **preview2**
- [ ] Stress and Scalability Testing Process **preview2**

## Theme for Preview2
- Not feature-complete, fundamentals-complete
- Test coverage:
  - [ ] Performance
  - [ ] Connection lifetime (timeouts, keep-alives, abnormal terminations...)
  - [ ] Security (e.g. connection IDs, leaks)

**Comment by anurse** [comment]
This issue is not helpful any more.
