### ISSUE TITLE
.NET Client To Do List

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR#51]
- [x] Add functional tests
- [x] ~Add generic overloads for the On method of the HubConnection~ - #311
- [x] Rename RpcConnection file to match HubConnection
- [x] Make sure we aren't getting the split messages issue as seen in https://github.com/aspnet/SignalR/issues/6
- [x] ~Clean up the public api~ - #311
- [x] Support WebSockets transport
- [x] ~Support SSE transport~ #309
- [x] ~handle cases where a method called from the server does not exist on the client~ - #312
- [x] ~client needs invoke overload for void methods~ - #311
- [x] ~re-usability of transports - currently the (longpolling transport) can be reused after it has been Disposed()~ #310
- [x] ~figure out ownership of transport - currently transports are passed to StartAsync and then Disposed in the Connection.Dispose() (maybe there should be a Stop() method?)~ -#310
- [x] re-entrancy - StartAsync on a transport should throw if the transport is already running
- [x] ~do we need to enable to close both Input/Output channels forcibly (example - right now if the user calls connection.Output.TryComplete(), connection.Input.Completion task will not be completed until the channel is drained) ?~ 
- [x] do we need Send method and Receive callback on Connection instead of exposing Input/Output - writing data/receiving data is really gross now with having to create messages and `PreservedBuffer`) - or make it easier to create/read from Message
- [x] do we need to track the state of the client? It is impossible to tell what state the client is in if the client is disconnected but the channel is not drained (this in turn makes it impossible to create the Closed event hanging on the Completion task)
- [x] do not expose channels (https://github.com/aspnet/SignalR/pull/141)
- [x] remove ContinueWith() (https://github.com/aspnet/SignalR/pull/141)
- [ ] consider removing the `Running` task from Transport - it's not part of interface and is a bit weird https://github.com/aspnet/SignalR/pull/141 - not doing at the moment - it is useful for testing.

**Comment by moozzyk** [comment]
Created individual issues - closing.
